# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_panel.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(895, 648)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(9, 39, 891, 581))
        self.tabWidget.setMinimumSize(QtCore.QSize(786, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(500000, 50000))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.list = QtWidgets.QWidget()
        self.list.setObjectName("list")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.list)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_list_main = QtWidgets.QFrame(self.list)
        self.frame_list_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_list_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_list_main.setObjectName("frame_list_main")
        self.scrollArea_book_list = QtWidgets.QScrollArea(self.frame_list_main)
        self.scrollArea_book_list.setGeometry(QtCore.QRect(10, 80, 751, 451))
        self.scrollArea_book_list.setWidgetResizable(True)
        self.scrollArea_book_list.setObjectName("scrollArea_book_list")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 749, 449))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName("gridLayout_5")
        for i in range(0,2):
            self.frame_list_0 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
            self.frame_list_0.setMaximumSize(QtCore.QSize(485, 150))
            self.frame_list_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
            self.frame_list_0.setFrameShadow(QtWidgets.QFrame.Raised)
            self.frame_list_0.setObjectName("frame_list_0")
            self.gridLayoutWidget = QtWidgets.QWidget(self.frame_list_0)
            self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 471, 136))
            self.gridLayoutWidget.setObjectName("gridLayoutWidget")
            self.gridLayout_list_0 = QtWidgets.QGridLayout(self.gridLayoutWidget)
            self.gridLayout_list_0.setContentsMargins(0, 0, 0, 0)
            self.gridLayout_list_0.setObjectName("gridLayout_list_0")
            self.label_list_name_0 = QtWidgets.QLabel(self.gridLayoutWidget)
            self.label_list_name_0.setObjectName("label_list_name_0")
            self.gridLayout_list_0.addWidget(self.label_list_name_0, 0, 0, 1, 1)
            self.label_list_quantity_0 = QtWidgets.QLabel(self.gridLayoutWidget)
            self.label_list_quantity_0.setObjectName("label_list_quantity_0")
            self.gridLayout_list_0.addWidget(self.label_list_quantity_0, 4, 0, 1, 1)
            self.label_list_author_0 = QtWidgets.QLabel(self.gridLayoutWidget)
            self.label_list_author_0.setObjectName("label_list_author_0")
            self.gridLayout_list_0.addWidget(self.label_list_author_0, 1, 0, 1, 1)
            self.label_list_price_0 = QtWidgets.QLabel(self.gridLayoutWidget)
            self.label_list_price_0.setObjectName("label_list_price_0")
            self.gridLayout_list_0.addWidget(self.label_list_price_0, 5, 0, 1, 1)
            self.label_list_publisher_0 = QtWidgets.QLabel(self.gridLayoutWidget)
            self.label_list_publisher_0.setObjectName("label_list_publisher_0")
            self.gridLayout_list_0.addWidget(self.label_list_publisher_0, 3, 0, 1, 1)
            self.btn_list_buy_0 = QtWidgets.QPushButton(self.gridLayoutWidget)
            self.btn_list_buy_0.setObjectName("btn_list_buy_0")
            self.gridLayout_list_0.addWidget(self.btn_list_buy_0, 6, 0, 1, 1)
            self.gridLayout_5.addWidget(self.frame_list_0, i, 1, 1, 1)
            self.list_picture_0 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
            self.list_picture_0.setMinimumSize(QtCore.QSize(220, 150))
            self.list_picture_0.setMaximumSize(QtCore.QSize(220, 150))
            self.list_picture_0.setObjectName("list_picture_0")
            self.gridLayout_5.addWidget(self.list_picture_0, i, 0, 1, 1)
        self.scrollArea_book_list.setWidget(self.scrollAreaWidgetContents)
        self.input_list_search = QtWidgets.QLineEdit(self.frame_list_main)
        self.input_list_search.setGeometry(QtCore.QRect(490, 20, 281, 24))
        self.input_list_search.setObjectName("input_list_search")
        self.btn_list_search = QtWidgets.QPushButton(self.frame_list_main)
        self.btn_list_search.setGeometry(QtCore.QRect(780, 20, 80, 24))
        self.btn_list_search.setObjectName("btn_list_search")
        self.checkBox_list_lp = QtWidgets.QCheckBox(self.frame_list_main)
        self.checkBox_list_lp.setGeometry(QtCore.QRect(10, 10, 91, 22))
        self.checkBox_list_lp.setObjectName("checkBox_list_lp")
        self.checkBox_list_ex = QtWidgets.QCheckBox(self.frame_list_main)
        self.checkBox_list_ex.setGeometry(QtCore.QRect(10, 40, 83, 22))
        self.checkBox_list_ex.setObjectName("checkBox_list_ex")
        self.checkBox_list_ms = QtWidgets.QCheckBox(self.frame_list_main)
        self.checkBox_list_ms.setGeometry(QtCore.QRect(120, 10, 83, 22))
        self.checkBox_list_ms.setObjectName("checkBox_list_ms")
        self.checkBox_list_ls = QtWidgets.QCheckBox(self.frame_list_main)
        self.checkBox_list_ls.setGeometry(QtCore.QRect(120, 40, 83, 22))
        self.checkBox_list_ls.setObjectName("checkBox_list_ls")
        self.btn_list_show = QtWidgets.QPushButton(self.frame_list_main)
        self.btn_list_show.setGeometry(QtCore.QRect(310, 20, 80, 24))
        self.btn_list_show.setObjectName("btn_list_show")
        self.checkBox_list_d = QtWidgets.QCheckBox(self.frame_list_main)
        self.checkBox_list_d.setGeometry(QtCore.QRect(220, 10, 83, 22))
        self.checkBox_list_d.setObjectName("checkBox_list_d")
        self.checkBox_list_q = QtWidgets.QCheckBox(self.frame_list_main)
        self.checkBox_list_q.setGeometry(QtCore.QRect(220, 40, 83, 22))
        self.checkBox_list_q.setObjectName("checkBox_list_q")
        self.gridLayout_6.addWidget(self.frame_list_main, 0, 0, 1, 1)
        self.tabWidget.addTab(self.list, "")
        self.categoreis = QtWidgets.QWidget()
        self.categoreis.setObjectName("categoreis")
        self.scrollArea_category = QtWidgets.QScrollArea(self.categoreis)
        self.scrollArea_category.setGeometry(QtCore.QRect(10, 120, 411, 421))
        self.scrollArea_category.setWidgetResizable(True)
        self.scrollArea_category.setObjectName("scrollArea_category")
        self.scrollAreaWidgetContents_category = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_category.setGeometry(QtCore.QRect(0, 0, 409, 419))
        self.scrollAreaWidgetContents_category.setObjectName("scrollAreaWidgetContents_category")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_category)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_category_main = QtWidgets.QGridLayout()
        self.gridLayout_category_main.setObjectName("gridLayout_category_main")
        self.frame_category_0 = QtWidgets.QFrame(self.scrollAreaWidgetContents_category)
        self.frame_category_0.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_category_0.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_category_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_category_0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_category_0.setObjectName("frame_category_0")
        self.label_category_0 = QtWidgets.QLabel(self.frame_category_0)
        self.label_category_0.setGeometry(QtCore.QRect(7, 9, 251, 31))
        self.label_category_0.setObjectName("label_category_0")
        self.btn_category_delete_0 = QtWidgets.QPushButton(self.frame_category_0)
        self.btn_category_delete_0.setGeometry(QtCore.QRect(270, 10, 80, 24))
        self.btn_category_delete_0.setObjectName("btn_category_delete_0")
        self.gridLayout_category_main.addWidget(self.frame_category_0, 0, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_category_main, 0, 0, 1, 1)
        self.scrollArea_category.setWidget(self.scrollAreaWidgetContents_category)
        self.input_category_add = QtWidgets.QLineEdit(self.categoreis)
        self.input_category_add.setGeometry(QtCore.QRect(10, 70, 251, 24))
        self.input_category_add.setObjectName("input_category_add")
        self.btn_category_add = QtWidgets.QPushButton(self.categoreis)
        self.btn_category_add.setGeometry(QtCore.QRect(290, 70, 80, 24))
        self.btn_category_add.setObjectName("btn_category_add")
        self.label_category_error = QtWidgets.QLabel(self.categoreis)
        self.label_category_error.setGeometry(QtCore.QRect(510, 420, 271, 31))
        self.label_category_error.setObjectName("label_category_error")
        self.label_category_title = QtWidgets.QLabel(self.categoreis)
        self.label_category_title.setGeometry(QtCore.QRect(380, 10, 181, 41))
        self.label_category_title.setObjectName("label_category_title")
        self.tabWidget.addTab(self.categoreis, "")
        self.publisher = QtWidgets.QWidget()
        self.publisher.setObjectName("publisher")
        self.frame_publisher_add = QtWidgets.QFrame(self.publisher)
        self.frame_publisher_add.setGeometry(QtCore.QRect(510, 70, 351, 211))
        self.frame_publisher_add.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_publisher_add.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_publisher_add.setObjectName("frame_publisher_add")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame_publisher_add)
        self.formLayoutWidget.setGeometry(QtCore.QRect(19, 29, 311, 181))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_publisher_main = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_publisher_main.setContentsMargins(0, 0, 0, 0)
        self.formLayout_publisher_main.setObjectName("formLayout_publisher_main")
        self.label_publisher_name = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_publisher_name.setObjectName("label_publisher_name")
        self.formLayout_publisher_main.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_publisher_name)
        self.input_publisher_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.input_publisher_name.setObjectName("input_publisher_name")
        self.formLayout_publisher_main.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_publisher_name)
        self.label_publisher_number = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_publisher_number.setObjectName("label_publisher_number")
        self.formLayout_publisher_main.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_publisher_number)
        self.input_publisher_number = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.input_publisher_number.setObjectName("input_publisher_number")
        self.formLayout_publisher_main.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.input_publisher_number)
        self.label_publisher_web = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_publisher_web.setObjectName("label_publisher_web")
        self.formLayout_publisher_main.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_publisher_web)
        self.input_publisher_web = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.input_publisher_web.setObjectName("input_publisher_web")
        self.formLayout_publisher_main.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.input_publisher_web)
        self.btn_publisher_add = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_publisher_add.setObjectName("btn_publisher_add")
        self.formLayout_publisher_main.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.btn_publisher_add)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_publisher_main.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_publisher_main.setItem(6, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_publisher_main.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_publisher_main.setItem(8, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.scrollArea_publisher_main = QtWidgets.QScrollArea(self.publisher)
        self.scrollArea_publisher_main.setGeometry(QtCore.QRect(10, 70, 411, 421))
        self.scrollArea_publisher_main.setWidgetResizable(True)
        self.scrollArea_publisher_main.setObjectName("scrollArea_publisher_main")
        self.scrollAreaWidgetContents_publisher = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_publisher.setGeometry(QtCore.QRect(0, 0, 409, 419))
        self.scrollAreaWidgetContents_publisher.setObjectName("scrollAreaWidgetContents_publisher")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_publisher)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gridLayout_publisher_main = QtWidgets.QGridLayout()
        self.gridLayout_publisher_main.setObjectName("gridLayout_publisher_main")
        self.frame_publisher_0 = QtWidgets.QFrame(self.scrollAreaWidgetContents_publisher)
        self.frame_publisher_0.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_publisher_0.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_publisher_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_publisher_0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_publisher_0.setObjectName("frame_publisher_0")
        self.label_publisher_name_0 = QtWidgets.QLabel(self.frame_publisher_0)
        self.label_publisher_name_0.setGeometry(QtCore.QRect(17, 9, 241, 31))
        self.label_publisher_name_0.setObjectName("label_publisher_name_0")
        self.btn_publisher_delete_0 = QtWidgets.QPushButton(self.frame_publisher_0)
        self.btn_publisher_delete_0.setGeometry(QtCore.QRect(270, 10, 80, 24))
        self.btn_publisher_delete_0.setObjectName("btn_publisher_delete_0")
        self.gridLayout_publisher_main.addWidget(self.frame_publisher_0, 0, 0, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_publisher_main, 0, 0, 1, 1)
        self.scrollArea_publisher_main.setWidget(self.scrollAreaWidgetContents_publisher)
        self.label_publisher_error = QtWidgets.QLabel(self.publisher)
        self.label_publisher_error.setGeometry(QtCore.QRect(580, 410, 271, 31))
        self.label_publisher_error.setObjectName("label_publisher_error")
        self.label_publisher_title = QtWidgets.QLabel(self.publisher)
        self.label_publisher_title.setGeometry(QtCore.QRect(340, 10, 181, 41))
        self.label_publisher_title.setObjectName("label_publisher_title")
        self.tabWidget.addTab(self.publisher, "")
        self.add = QtWidgets.QWidget()
        self.add.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.add.setObjectName("add")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.add)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_addbook_error = QtWidgets.QLabel(self.add)
        self.label_addbook_error.setObjectName("label_addbook_error")
        self.gridLayout_3.addWidget(self.label_addbook_error, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_addbook_main = QtWidgets.QGridLayout()
        self.gridLayout_addbook_main.setObjectName("gridLayout_addbook_main")
        self.label_addbook_name = QtWidgets.QLabel(self.add)
        self.label_addbook_name.setObjectName("label_addbook_name")
        self.gridLayout_addbook_main.addWidget(self.label_addbook_name, 0, 0, 1, 1)
        self.label_addbook_picture = QtWidgets.QLabel(self.add)
        self.label_addbook_picture.setObjectName("label_addbook_picture")
        self.gridLayout_addbook_main.addWidget(self.label_addbook_picture, 7, 0, 1, 1)
        self.label_addbook_author = QtWidgets.QLabel(self.add)
        self.label_addbook_author.setObjectName("label_addbook_author")
        self.gridLayout_addbook_main.addWidget(self.label_addbook_author, 1, 0, 1, 1)
        self.input_publisher_name_2 = QtWidgets.QLineEdit(self.add)
        self.input_publisher_name_2.setObjectName("input_publisher_name_2")
        self.gridLayout_addbook_main.addWidget(self.input_publisher_name_2, 0, 1, 1, 1)
        self.input_publisher_author = QtWidgets.QLineEdit(self.add)
        self.input_publisher_author.setObjectName("input_publisher_author")
        self.gridLayout_addbook_main.addWidget(self.input_publisher_author, 1, 1, 1, 1)
        self.label_addbook_category = QtWidgets.QLabel(self.add)
        self.label_addbook_category.setObjectName("label_addbook_category")
        self.gridLayout_addbook_main.addWidget(self.label_addbook_category, 6, 0, 1, 1)
        self.label_addbook_description = QtWidgets.QLabel(self.add)
        self.label_addbook_description.setObjectName("label_addbook_description")
        self.gridLayout_addbook_main.addWidget(self.label_addbook_description, 4, 0, 1, 1)
        self.plainTextEdit_publisher_description = QtWidgets.QPlainTextEdit(self.add)
        self.plainTextEdit_publisher_description.setObjectName("plainTextEdit_publisher_description")
        self.gridLayout_addbook_main.addWidget(self.plainTextEdit_publisher_description, 4, 1, 1, 1)
        self.select_addbook_publisher = QtWidgets.QComboBox(self.add)
        self.select_addbook_publisher.setObjectName("select_addbook_publisher")
        self.select_addbook_publisher.addItem("")
        self.gridLayout_addbook_main.addWidget(self.select_addbook_publisher, 5, 1, 1, 1)
        self.input_publisher_quantity = QtWidgets.QLineEdit(self.add)
        self.input_publisher_quantity.setObjectName("input_publisher_quantity")
        self.gridLayout_addbook_main.addWidget(self.input_publisher_quantity, 3, 1, 1, 1)
        self.scrollArea_addbook_category = QtWidgets.QScrollArea(self.add)
        self.scrollArea_addbook_category.setWidgetResizable(True)
        self.scrollArea_addbook_category.setObjectName("scrollArea_addbook_category")
        self.scrollAreaWidgetContents_addbook_main = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_addbook_main.setGeometry(QtCore.QRect(0, 0, 777, 72))
        self.scrollAreaWidgetContents_addbook_main.setObjectName("scrollAreaWidgetContents_addbook_main")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_addbook_main)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_addbook_category_0 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_addbook_main)
        self.checkBox_addbook_category_0.setObjectName("checkBox_addbook_category_0")
        self.gridLayout_4.addWidget(self.checkBox_addbook_category_0, 0, 0, 1, 1)
        self.scrollArea_addbook_category.setWidget(self.scrollAreaWidgetContents_addbook_main)
        self.gridLayout_addbook_main.addWidget(self.scrollArea_addbook_category, 6, 1, 1, 1)
        self.label_addbook_quantity = QtWidgets.QLabel(self.add)
        self.label_addbook_quantity.setObjectName("label_addbook_quantity")
        self.gridLayout_addbook_main.addWidget(self.label_addbook_quantity, 3, 0, 1, 1)
        self.btn_addbook_submit = QtWidgets.QPushButton(self.add)
        self.btn_addbook_submit.setObjectName("btn_addbook_submit")
        self.gridLayout_addbook_main.addWidget(self.btn_addbook_submit, 8, 1, 1, 1)
        self.label_addbook_publisher = QtWidgets.QLabel(self.add)
        self.label_addbook_publisher.setObjectName("label_addbook_publisher")
        self.gridLayout_addbook_main.addWidget(self.label_addbook_publisher, 5, 0, 1, 1)
        self.input_publisher_price = QtWidgets.QLineEdit(self.add)
        self.input_publisher_price.setObjectName("input_publisher_price")
        self.gridLayout_addbook_main.addWidget(self.input_publisher_price, 2, 1, 1, 1)
        self.label_addbook_price = QtWidgets.QLabel(self.add)
        self.label_addbook_price.setObjectName("label_addbook_price")
        self.gridLayout_addbook_main.addWidget(self.label_addbook_price, 2, 0, 1, 1)
        self.frame_addbook_picture = QtWidgets.QFrame(self.add)
        self.frame_addbook_picture.setMinimumSize(QtCore.QSize(0, 38))
        self.frame_addbook_picture.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_addbook_picture.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_addbook_picture.setObjectName("frame_addbook_picture")
        self.btn_addbook_broswer = QtWidgets.QPushButton(self.frame_addbook_picture)
        self.btn_addbook_broswer.setGeometry(QtCore.QRect(510, 10, 80, 21))
        self.btn_addbook_broswer.setObjectName("btn_addbook_broswer")
        self.input_addbook_picture = QtWidgets.QLineEdit(self.frame_addbook_picture)
        self.input_addbook_picture.setGeometry(QtCore.QRect(0, 10, 500, 21))
        self.input_addbook_picture.setMinimumSize(QtCore.QSize(500, 0))
        self.input_addbook_picture.setObjectName("input_addbook_picture")
        self.gridLayout_addbook_main.addWidget(self.frame_addbook_picture, 7, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_addbook_main, 2, 0, 1, 1)
        self.label_addbook_title = QtWidgets.QLabel(self.add)
        self.label_addbook_title.setObjectName("label_addbook_title")
        self.gridLayout_3.addWidget(self.label_addbook_title, 1, 0, 1, 1)
        self.tabWidget.addTab(self.add, "")
        self.users = QtWidgets.QWidget()
        self.users.setObjectName("users")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.users)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_user_main = QtWidgets.QFrame(self.users)
        self.frame_user_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_user_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_user_main.setObjectName("frame_user_main")
        self.input_user_search = QtWidgets.QLineEdit(self.frame_user_main)
        self.input_user_search.setGeometry(QtCore.QRect(480, 20, 281, 24))
        self.input_user_search.setObjectName("input_user_search")
        self.btn_user_search = QtWidgets.QPushButton(self.frame_user_main)
        self.btn_user_search.setGeometry(QtCore.QRect(770, 20, 80, 24))
        self.btn_user_search.setObjectName("btn_user_search")
        self.scrollArea_user = QtWidgets.QScrollArea(self.frame_user_main)
        self.scrollArea_user.setGeometry(QtCore.QRect(10, 70, 871, 461))
        self.scrollArea_user.setWidgetResizable(True)
        self.scrollArea_user.setObjectName("scrollArea_user")
        self.scrollAreaWidgetContents_user_main = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_user_main.setGeometry(QtCore.QRect(0, 0, 869, 459))
        self.scrollAreaWidgetContents_user_main.setObjectName("scrollAreaWidgetContents_user_main")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_user_main)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_user_0 = QtWidgets.QFrame(self.scrollAreaWidgetContents_user_main)
        self.frame_user_0.setMinimumSize(QtCore.QSize(839, 65))
        self.frame_user_0.setMaximumSize(QtCore.QSize(839, 65))
        self.frame_user_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_user_0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_user_0.setObjectName("frame_user_0")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.frame_user_0)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 821, 52))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_user_0 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_user_0.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_user_0.setObjectName("gridLayout_user_0")
        self.btn_user_update_0 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btn_user_update_0.setMaximumSize(QtCore.QSize(55, 16777215))
        self.btn_user_update_0.setObjectName("btn_user_update_0")
        self.gridLayout_user_0.addWidget(self.btn_user_update_0, 0, 6, 1, 1)
        self.label_user_address_0 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_user_address_0.setMinimumSize(QtCore.QSize(100, 0))
        self.label_user_address_0.setMaximumSize(QtCore.QSize(150, 50))
        self.label_user_address_0.setObjectName("label_user_address_0")
        self.gridLayout_user_0.addWidget(self.label_user_address_0, 0, 4, 1, 1)
        self.btn_user_delete_0 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btn_user_delete_0.setMaximumSize(QtCore.QSize(55, 16777215))
        self.btn_user_delete_0.setObjectName("btn_user_delete_0")
        self.gridLayout_user_0.addWidget(self.btn_user_delete_0, 0, 7, 1, 1)
        self.label_user_lastname_0 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_user_lastname_0.setMinimumSize(QtCore.QSize(83, 50))
        self.label_user_lastname_0.setMaximumSize(QtCore.QSize(83, 50))
        self.label_user_lastname_0.setObjectName("label_user_lastname_0")
        self.gridLayout_user_0.addWidget(self.label_user_lastname_0, 0, 1, 1, 1)
        self.label_user_isadmin_0 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_user_isadmin_0.setMinimumSize(QtCore.QSize(55, 50))
        self.label_user_isadmin_0.setMaximumSize(QtCore.QSize(55, 50))
        self.label_user_isadmin_0.setObjectName("label_user_isadmin_0")
        self.gridLayout_user_0.addWidget(self.label_user_isadmin_0, 0, 5, 1, 1)
        self.label_user_phone_0 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_user_phone_0.setMinimumSize(QtCore.QSize(83, 50))
        self.label_user_phone_0.setMaximumSize(QtCore.QSize(83, 50))
        self.label_user_phone_0.setObjectName("label_user_phone_0")
        self.gridLayout_user_0.addWidget(self.label_user_phone_0, 0, 3, 1, 1)
        self.label_user_username_0 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_user_username_0.setMinimumSize(QtCore.QSize(83, 50))
        self.label_user_username_0.setMaximumSize(QtCore.QSize(83, 50))
        self.label_user_username_0.setObjectName("label_user_username_0")
        self.gridLayout_user_0.addWidget(self.label_user_username_0, 0, 2, 1, 1)
        self.label_user_name_0 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_user_name_0.setMinimumSize(QtCore.QSize(83, 50))
        self.label_user_name_0.setMaximumSize(QtCore.QSize(83, 50))
        self.label_user_name_0.setObjectName("label_user_name_0")
        self.gridLayout_user_0.addWidget(self.label_user_name_0, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_user_0, 1, 0, 1, 1, QtCore.Qt.AlignTop)
        self.frame_user_header = QtWidgets.QFrame(self.scrollAreaWidgetContents_user_main)
        self.frame_user_header.setEnabled(True)
        self.frame_user_header.setMinimumSize(QtCore.QSize(839, 65))
        self.frame_user_header.setMaximumSize(QtCore.QSize(730, 65))
        self.frame_user_header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_user_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_user_header.setObjectName("frame_user_header")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame_user_header)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(9, 9, 821, 52))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_user_header = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_user_header.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_user_header.setObjectName("gridLayout_user_header")
        self.label_user_phone = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_user_phone.setMinimumSize(QtCore.QSize(83, 50))
        self.label_user_phone.setMaximumSize(QtCore.QSize(83, 50))
        self.label_user_phone.setObjectName("label_user_phone")
        self.gridLayout_user_header.addWidget(self.label_user_phone, 0, 3, 1, 1)
        self.label_user_name = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_user_name.setMinimumSize(QtCore.QSize(83, 50))
        self.label_user_name.setMaximumSize(QtCore.QSize(83, 50))
        self.label_user_name.setObjectName("label_user_name")
        self.gridLayout_user_header.addWidget(self.label_user_name, 0, 0, 1, 1)
        self.label_user_delete = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_user_delete.setMinimumSize(QtCore.QSize(55, 50))
        self.label_user_delete.setMaximumSize(QtCore.QSize(55, 16777215))
        self.label_user_delete.setObjectName("label_user_delete")
        self.gridLayout_user_header.addWidget(self.label_user_delete, 0, 7, 1, 1)
        self.label_user_lastname = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_user_lastname.setMinimumSize(QtCore.QSize(83, 50))
        self.label_user_lastname.setMaximumSize(QtCore.QSize(83, 50))
        self.label_user_lastname.setObjectName("label_user_lastname")
        self.gridLayout_user_header.addWidget(self.label_user_lastname, 0, 1, 1, 1)
        self.label_user_username = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_user_username.setMinimumSize(QtCore.QSize(83, 50))
        self.label_user_username.setMaximumSize(QtCore.QSize(83, 50))
        self.label_user_username.setObjectName("label_user_username")
        self.gridLayout_user_header.addWidget(self.label_user_username, 0, 2, 1, 1)
        self.label_user_update = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_user_update.setMinimumSize(QtCore.QSize(55, 50))
        self.label_user_update.setMaximumSize(QtCore.QSize(55, 16777215))
        self.label_user_update.setObjectName("label_user_update")
        self.gridLayout_user_header.addWidget(self.label_user_update, 0, 6, 1, 1)
        self.label_user_address = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_user_address.setMinimumSize(QtCore.QSize(150, 0))
        self.label_user_address.setMaximumSize(QtCore.QSize(150, 50))
        self.label_user_address.setObjectName("label_user_address")
        self.gridLayout_user_header.addWidget(self.label_user_address, 0, 4, 1, 1)
        self.label_user_isadmin = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_user_isadmin.setMinimumSize(QtCore.QSize(55, 50))
        self.label_user_isadmin.setMaximumSize(QtCore.QSize(55, 16777215))
        self.label_user_isadmin.setObjectName("label_user_isadmin")
        self.gridLayout_user_header.addWidget(self.label_user_isadmin, 0, 5, 1, 1)
        self.gridLayout_9.addWidget(self.frame_user_header, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.scrollArea_user.setWidget(self.scrollAreaWidgetContents_user_main)
        self.checkBox_user_mb = QtWidgets.QCheckBox(self.frame_user_main)
        self.checkBox_user_mb.setGeometry(QtCore.QRect(10, 10, 91, 22))
        self.checkBox_user_mb.setObjectName("checkBox_user_mb")
        self.checkBox_user_wb = QtWidgets.QCheckBox(self.frame_user_main)
        self.checkBox_user_wb.setGeometry(QtCore.QRect(10, 40, 91, 22))
        self.checkBox_user_wb.setObjectName("checkBox_user_wb")
        self.checkBox_user_admin = QtWidgets.QCheckBox(self.frame_user_main)
        self.checkBox_user_admin.setGeometry(QtCore.QRect(140, 10, 83, 22))
        self.checkBox_user_admin.setObjectName("checkBox_user_admin")
        self.checkBox_user_da = QtWidgets.QCheckBox(self.frame_user_main)
        self.checkBox_user_da.setGeometry(QtCore.QRect(140, 40, 91, 22))
        self.checkBox_user_da.setObjectName("checkBox_user_da")
        self.btn_user_show = QtWidgets.QPushButton(self.frame_user_main)
        self.btn_user_show.setGeometry(QtCore.QRect(260, 20, 80, 24))
        self.btn_user_show.setObjectName("btn_user_show")
        self.gridLayout_8.addWidget(self.frame_user_main, 0, 0, 1, 1)
        self.tabWidget.addTab(self.users, "")
        self.orders = QtWidgets.QWidget()
        self.orders.setObjectName("orders")
        self.tableWidget_order = QtWidgets.QTableWidget(self.orders)
        self.tableWidget_order.setGeometry(QtCore.QRect(34, 50, 811, 481))
        self.tableWidget_order.setObjectName("tableWidget_order")
        self.tableWidget_order.setColumnCount(8)
        self.tableWidget_order.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_order.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_order.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_order.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_order.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_order.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_order.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_order.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_order.setItem(0, 7, item)
        self.label_order_title = QtWidgets.QLabel(self.orders)
        self.label_order_title.setGeometry(QtCore.QRect(320, 9, 181, 41))
        self.label_order_title.setObjectName("label_order_title")
        self.tabWidget.addTab(self.orders, "")
        self.inventory = QtWidgets.QWidget()
        self.inventory.setObjectName("inventory")
        self.scrollArea_inventory_main = QtWidgets.QScrollArea(self.inventory)
        self.scrollArea_inventory_main.setGeometry(QtCore.QRect(155, 89, 601, 411))
        self.scrollArea_inventory_main.setWidgetResizable(True)
        self.scrollArea_inventory_main.setObjectName("scrollArea_inventory_main")
        self.scrollAreaWidgetContents_inventory = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_inventory.setGeometry(QtCore.QRect(0, 0, 599, 409))
        self.scrollAreaWidgetContents_inventory.setObjectName("scrollAreaWidgetContents_inventory")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents_inventory)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 581, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_inventory_main = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_inventory_main.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_inventory_main.setObjectName("verticalLayout_inventory_main")
        self.frame_inventory_0 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_inventory_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inventory_0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inventory_0.setObjectName("frame_inventory_0")
        self.label_inventory_title_0 = QtWidgets.QLabel(self.frame_inventory_0)
        self.label_inventory_title_0.setGeometry(QtCore.QRect(20, 10, 200, 41))
        self.label_inventory_title_0.setObjectName("label_inventory_title_0")
        self.label_inventory_0 = QtWidgets.QLabel(self.frame_inventory_0)
        self.label_inventory_0.setGeometry(QtCore.QRect(250, 10, 180, 40))
        self.label_inventory_0.setObjectName("label_inventory_0")
        self.verticalLayout_inventory_main.addWidget(self.frame_inventory_0)
        self.frame_inventory_1 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_inventory_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inventory_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inventory_1.setObjectName("frame_inventory_1")
        self.label_inventory_title_1 = QtWidgets.QLabel(self.frame_inventory_1)
        self.label_inventory_title_1.setGeometry(QtCore.QRect(20, 10, 200, 41))
        self.label_inventory_title_1.setObjectName("label_inventory_title_1")
        self.label_inventory_1 = QtWidgets.QLabel(self.frame_inventory_1)
        self.label_inventory_1.setGeometry(QtCore.QRect(250, 10, 180, 40))
        self.label_inventory_1.setObjectName("label_inventory_1")
        self.verticalLayout_inventory_main.addWidget(self.frame_inventory_1)
        self.frame_inventory_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_inventory_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inventory_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inventory_2.setObjectName("frame_inventory_2")
        self.label_inventory_title_2 = QtWidgets.QLabel(self.frame_inventory_2)
        self.label_inventory_title_2.setGeometry(QtCore.QRect(20, 10, 200, 41))
        self.label_inventory_title_2.setObjectName("label_inventory_title_2")
        self.label_inventory_2 = QtWidgets.QLabel(self.frame_inventory_2)
        self.label_inventory_2.setGeometry(QtCore.QRect(250, 10, 180, 40))
        self.label_inventory_2.setObjectName("label_inventory_2")
        self.verticalLayout_inventory_main.addWidget(self.frame_inventory_2)
        self.frame_inventory_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_inventory_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inventory_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inventory_3.setObjectName("frame_inventory_3")
        self.label_inventory_title_3 = QtWidgets.QLabel(self.frame_inventory_3)
        self.label_inventory_title_3.setGeometry(QtCore.QRect(20, 10, 200, 41))
        self.label_inventory_title_3.setObjectName("label_inventory_title_3")
        self.label_inventory_3 = QtWidgets.QLabel(self.frame_inventory_3)
        self.label_inventory_3.setGeometry(QtCore.QRect(250, 10, 180, 40))
        self.label_inventory_3.setObjectName("label_inventory_3")
        self.verticalLayout_inventory_main.addWidget(self.frame_inventory_3)
        self.frame_inventory_4 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_inventory_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inventory_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inventory_4.setObjectName("frame_inventory_4")
        self.label_inventory_title_4 = QtWidgets.QLabel(self.frame_inventory_4)
        self.label_inventory_title_4.setGeometry(QtCore.QRect(20, 10, 200, 41))
        self.label_inventory_title_4.setObjectName("label_inventory_title_4")
        self.label_inventory_4 = QtWidgets.QLabel(self.frame_inventory_4)
        self.label_inventory_4.setGeometry(QtCore.QRect(250, 10, 180, 40))
        self.label_inventory_4.setObjectName("label_inventory_4")
        self.verticalLayout_inventory_main.addWidget(self.frame_inventory_4)
        self.frame_inventory_5 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_inventory_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inventory_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inventory_5.setObjectName("frame_inventory_5")
        self.label_inventory_title_5 = QtWidgets.QLabel(self.frame_inventory_5)
        self.label_inventory_title_5.setGeometry(QtCore.QRect(20, 10, 200, 41))
        self.label_inventory_title_5.setObjectName("label_inventory_title_5")
        self.label_inventory_5 = QtWidgets.QLabel(self.frame_inventory_5)
        self.label_inventory_5.setGeometry(QtCore.QRect(250, 10, 180, 40))
        self.label_inventory_5.setObjectName("label_inventory_5")
        self.verticalLayout_inventory_main.addWidget(self.frame_inventory_5)
        self.scrollArea_inventory_main.setWidget(self.scrollAreaWidgetContents_inventory)
        self.label_inventory_title = QtWidgets.QLabel(self.inventory)
        self.label_inventory_title.setGeometry(QtCore.QRect(340, 30, 231, 41))
        self.label_inventory_title.setObjectName("label_inventory_title")
        self.tabWidget.addTab(self.inventory, "")
        self.btn_logout = QtWidgets.QPushButton(self.centralwidget)
        self.btn_logout.setGeometry(QtCore.QRect(800, 10, 80, 24))
        self.btn_logout.setObjectName("btn_logout")
        self.label_login_username = QtWidgets.QLabel(self.centralwidget)
        self.label_login_username.setGeometry(QtCore.QRect(10, 10, 201, 16))
        self.label_login_username.setObjectName("label_login_username")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.btn_list_show.clicked.connect(MainWindow.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_list_name_0.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Harry Patter</span></p></body></html>"))
        self.label_list_quantity_0.setText(_translate("MainWindow", "<html><head/><body><p>quntity : 25</p></body></html>"))
        self.label_list_author_0.setText(_translate("MainWindow", "<html><head/><body><p>by : Wilson miler</p></body></html>"))
        self.label_list_price_0.setText(_translate("MainWindow", "<html><head/><body><p>price : 12000 $</p></body></html>"))
        self.label_list_publisher_0.setText(_translate("MainWindow", "<html><head/><body><p>Publisher : tolo</p></body></html>"))
        self.btn_list_buy_0.setText(_translate("MainWindow", "Buy"))
        self.btn_list_search.setText(_translate("MainWindow", "Search"))
        self.checkBox_list_lp.setText(_translate("MainWindow", "lowest price"))
        self.checkBox_list_ex.setText(_translate("MainWindow", "expensive"))
        self.checkBox_list_ms.setText(_translate("MainWindow", "Most Sold"))
        self.checkBox_list_ls.setText(_translate("MainWindow", "Least Sold"))
        self.btn_list_show.setText(_translate("MainWindow", "Show"))
        self.checkBox_list_d.setText(_translate("MainWindow", "Date"))
        self.checkBox_list_q.setText(_translate("MainWindow", "quantity"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.list), _translate("MainWindow", "Book List"))
        self.label_category_0.setText(_translate("MainWindow", "action"))
        self.btn_category_delete_0.setText(_translate("MainWindow", "Delete"))
        self.btn_category_add.setText(_translate("MainWindow", "Add"))
        self.label_category_error.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Error</p></body></html>"))
        self.label_category_title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Publishers</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.categoreis), _translate("MainWindow", "Categorys"))
        self.label_publisher_name.setText(_translate("MainWindow", "Name"))
        self.label_publisher_number.setText(_translate("MainWindow", "Phone Number"))
        self.label_publisher_web.setText(_translate("MainWindow", "Web site"))
        self.btn_publisher_add.setText(_translate("MainWindow", "Add"))
        self.label_publisher_name_0.setText(_translate("MainWindow", "tolo"))
        self.btn_publisher_delete_0.setText(_translate("MainWindow", "Delete"))
        self.label_publisher_error.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Error</p></body></html>"))
        self.label_publisher_title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Publishers</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.publisher), _translate("MainWindow", "Publisher"))
        self.label_addbook_error.setText(_translate("MainWindow", "error"))
        self.label_addbook_name.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">name</span></p></body></html>"))
        self.label_addbook_picture.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Picture</span></p></body></html>"))
        self.label_addbook_author.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">author</span></p></body></html>"))
        self.label_addbook_category.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">category</span></p></body></html>"))
        self.label_addbook_description.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">description</span></p><p align=\"center\"><br/></p></body></html>"))
        self.select_addbook_publisher.setItemText(0, _translate("MainWindow", "advanture"))
        self.checkBox_addbook_category_0.setText(_translate("MainWindow", "CheckBox"))
        self.label_addbook_quantity.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">quantity</span></p></body></html>"))
        self.btn_addbook_submit.setText(_translate("MainWindow", "Submit"))
        self.label_addbook_publisher.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">pulisher</span></p></body></html>"))
        self.label_addbook_price.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">price</span></p></body></html>"))
        self.btn_addbook_broswer.setText(_translate("MainWindow", "Broswer"))
        self.label_addbook_title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">add books</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.add), _translate("MainWindow", "Add Book"))
        self.btn_user_search.setText(_translate("MainWindow", "Search"))
        self.btn_user_update_0.setText(_translate("MainWindow", "Update"))
        self.label_user_address_0.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">iran ,tehran mumuim hjmjm jm jm </p></body></html>"))
        self.btn_user_delete_0.setText(_translate("MainWindow", "Delete"))
        self.label_user_lastname_0.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Noroozi</p></body></html>"))
        self.label_user_isadmin_0.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Yes</p></body></html>"))
        self.label_user_phone_0.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">091245896</p></body></html>"))
        self.label_user_username_0.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Norouzy</p></body></html>"))
        self.label_user_name_0.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Mohamad</p></body></html>"))
        self.label_user_phone.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Phone</span></p></body></html>"))
        self.label_user_name.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">name</span></p></body></html>"))
        self.label_user_delete.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Delete</span></p></body></html>"))
        self.label_user_lastname.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Last Name</span></p></body></html>"))
        self.label_user_username.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Username</span></p></body></html>"))
        self.label_user_update.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Update</span></p></body></html>"))
        self.label_user_address.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Address</span></p></body></html>"))
        self.label_user_isadmin.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Is Admin</span></p></body></html>"))
        self.checkBox_user_mb.setText(_translate("MainWindow", "Most Buyer"))
        self.checkBox_user_wb.setText(_translate("MainWindow", "Weak Buyer"))
        self.checkBox_user_admin.setText(_translate("MainWindow", "admin"))
        self.checkBox_user_da.setText(_translate("MainWindow", "Date Added"))
        self.btn_user_show.setText(_translate("MainWindow", "Show"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.users), _translate("MainWindow", "Users"))
        item = self.tableWidget_order.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_order.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget_order.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Book"))
        item = self.tableWidget_order.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "User"))
        item = self.tableWidget_order.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Publisher"))
        item = self.tableWidget_order.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date added"))
        item = self.tableWidget_order.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.tableWidget_order.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Price"))
        item = self.tableWidget_order.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Total Price"))
        __sortingEnabled = self.tableWidget_order.isSortingEnabled()
        self.tableWidget_order.setSortingEnabled(False)
        item = self.tableWidget_order.item(0, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_order.item(0, 1)
        item.setText(_translate("MainWindow", "Harry"))
        item = self.tableWidget_order.item(0, 2)
        item.setText(_translate("MainWindow", "Nrouzy"))
        item = self.tableWidget_order.item(0, 3)
        item.setText(_translate("MainWindow", "tolo"))
        item = self.tableWidget_order.item(0, 4)
        item.setText(_translate("MainWindow", "12/03/9"))
        item = self.tableWidget_order.item(0, 5)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_order.item(0, 6)
        item.setText(_translate("MainWindow", "1200"))
        item = self.tableWidget_order.item(0, 7)
        item.setText(_translate("MainWindow", "2400"))
        self.tableWidget_order.setSortingEnabled(__sortingEnabled)
        self.label_order_title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">All Orders</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.orders), _translate("MainWindow", "Orders"))
        self.label_inventory_title_0.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Books Total Quantity :</span></p></body></html>"))
        self.label_inventory_0.setText(_translate("MainWindow", "12"))
        self.label_inventory_title_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Sold Books Quantity :</span></p></body></html>"))
        self.label_inventory_1.setText(_translate("MainWindow", "3"))
        self.label_inventory_title_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Total prices of books sold :</span></p></body></html>"))
        self.label_inventory_2.setText(_translate("MainWindow", "18000"))
        self.label_inventory_title_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Most books sold :</span></p></body></html>"))
        self.label_inventory_3.setText(_translate("MainWindow", "harry"))
        self.label_inventory_title_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">The least sold book :</span></p></body></html>"))
        self.label_inventory_4.setText(_translate("MainWindow", "perspolice"))
        self.label_inventory_title_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">The user who bought the most :</span></p></body></html>"))
        self.label_inventory_5.setText(_translate("MainWindow", "norouzy"))
        self.label_inventory_title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Online Book Store Info</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.inventory), _translate("MainWindow", "Inventory"))
        self.btn_logout.setText(_translate("MainWindow", "Log out"))
        self.label_login_username.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Norouzy</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
