# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_panel.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(895, 648)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.user_info = QtWidgets.QTabWidget(self.centralwidget)
        self.user_info.setEnabled(True)
        self.user_info.setGeometry(QtCore.QRect(9, 39, 891, 581))
        self.user_info.setMinimumSize(QtCore.QSize(786, 0))
        self.user_info.setMaximumSize(QtCore.QSize(500000, 50000))
        self.user_info.setStyleSheet("")
        self.user_info.setTabPosition(QtWidgets.QTabWidget.North)
        self.user_info.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.user_info.setObjectName("user_info")
        self.list = QtWidgets.QWidget()
        self.list.setObjectName("list")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.list)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_list_main = QtWidgets.QFrame(self.list)
        self.frame_list_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_list_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_list_main.setObjectName("frame_list_main")
        self.scrollArea_book_list = QtWidgets.QScrollArea(self.frame_list_main)
        self.scrollArea_book_list.setGeometry(QtCore.QRect(10, 80, 751, 451))
        self.scrollArea_book_list.setWidgetResizable(True)
        self.scrollArea_book_list.setObjectName("scrollArea_book_list")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 749, 449))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_list_0 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_list_0.setMaximumSize(QtCore.QSize(485, 150))
        self.frame_list_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_list_0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_list_0.setObjectName("frame_list_0")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame_list_0)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 471, 136))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_list_0 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_list_0.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_list_0.setObjectName("gridLayout_list_0")
        self.label_list_name_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_list_name_0.setObjectName("label_list_name_0")
        self.gridLayout_list_0.addWidget(self.label_list_name_0, 0, 0, 1, 1)
        self.label_list_quantity_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_list_quantity_0.setObjectName("label_list_quantity_0")
        self.gridLayout_list_0.addWidget(self.label_list_quantity_0, 4, 0, 1, 1)
        self.label_list_author_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_list_author_0.setObjectName("label_list_author_0")
        self.gridLayout_list_0.addWidget(self.label_list_author_0, 1, 0, 1, 1)
        self.label_list_price_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_list_price_0.setObjectName("label_list_price_0")
        self.gridLayout_list_0.addWidget(self.label_list_price_0, 5, 0, 1, 1)
        self.label_list_publisher_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_list_publisher_0.setObjectName("label_list_publisher_0")
        self.gridLayout_list_0.addWidget(self.label_list_publisher_0, 3, 0, 1, 1)
        self.btn_list_buy_0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_list_buy_0.setObjectName("btn_list_buy_0")
        self.gridLayout_list_0.addWidget(self.btn_list_buy_0, 6, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_list_0, 0, 1, 1, 1)
        self.list_picture_0 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.list_picture_0.setMinimumSize(QtCore.QSize(220, 150))
        self.list_picture_0.setMaximumSize(QtCore.QSize(220, 150))
        self.list_picture_0.setObjectName("list_picture_0")
        self.gridLayout_5.addWidget(self.list_picture_0, 0, 0, 1, 1)
        self.scrollArea_book_list.setWidget(self.scrollAreaWidgetContents)
        self.input_list_search = QtWidgets.QLineEdit(self.frame_list_main)
        self.input_list_search.setGeometry(QtCore.QRect(490, 20, 281, 24))
        self.input_list_search.setObjectName("input_list_search")
        self.btn_list_search = QtWidgets.QPushButton(self.frame_list_main)
        self.btn_list_search.setGeometry(QtCore.QRect(780, 20, 80, 24))
        self.btn_list_search.setObjectName("btn_list_search")
        self.checkBox_list_lp = QtWidgets.QCheckBox(self.frame_list_main)
        self.checkBox_list_lp.setGeometry(QtCore.QRect(10, 10, 91, 22))
        self.checkBox_list_lp.setObjectName("checkBox_list_lp")
        self.checkBox_list_ex = QtWidgets.QCheckBox(self.frame_list_main)
        self.checkBox_list_ex.setGeometry(QtCore.QRect(10, 40, 83, 22))
        self.checkBox_list_ex.setObjectName("checkBox_list_ex")
        self.checkBox_list_ms = QtWidgets.QCheckBox(self.frame_list_main)
        self.checkBox_list_ms.setGeometry(QtCore.QRect(120, 10, 83, 22))
        self.checkBox_list_ms.setObjectName("checkBox_list_ms")
        self.checkBox_list_ls = QtWidgets.QCheckBox(self.frame_list_main)
        self.checkBox_list_ls.setGeometry(QtCore.QRect(120, 40, 83, 22))
        self.checkBox_list_ls.setObjectName("checkBox_list_ls")
        self.btn_list_show = QtWidgets.QPushButton(self.frame_list_main)
        self.btn_list_show.setGeometry(QtCore.QRect(310, 20, 80, 24))
        self.btn_list_show.setObjectName("btn_list_show")
        self.checkBox_list_d = QtWidgets.QCheckBox(self.frame_list_main)
        self.checkBox_list_d.setGeometry(QtCore.QRect(220, 10, 83, 22))
        self.checkBox_list_d.setObjectName("checkBox_list_d")
        self.checkBox_list_q = QtWidgets.QCheckBox(self.frame_list_main)
        self.checkBox_list_q.setGeometry(QtCore.QRect(220, 40, 83, 22))
        self.checkBox_list_q.setObjectName("checkBox_list_q")
        self.gridLayout_6.addWidget(self.frame_list_main, 0, 0, 1, 1)
        self.user_info.addTab(self.list, "")
        self.orders = QtWidgets.QWidget()
        self.orders.setObjectName("orders")
        self.tableWidget_order = QtWidgets.QTableWidget(self.orders)
        self.tableWidget_order.setGeometry(QtCore.QRect(34, 50, 811, 481))
        self.tableWidget_order.setObjectName("tableWidget_order")
        self.tableWidget_order.setColumnCount(8)
        self.tableWidget_order.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_order.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_order.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_order.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_order.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_order.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_order.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_order.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_order.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_order.setItem(0, 7, item)
        self.label_order_title = QtWidgets.QLabel(self.orders)
        self.label_order_title.setGeometry(QtCore.QRect(320, 9, 181, 41))
        self.label_order_title.setObjectName("label_order_title")
        self.user_info.addTab(self.orders, "")
        self.user_info1 = QtWidgets.QWidget()
        self.user_info1.setObjectName("user_info1")
        self.label_inventory_title = QtWidgets.QLabel(self.user_info1)
        self.label_inventory_title.setGeometry(QtCore.QRect(340, 30, 231, 41))
        self.label_inventory_title.setObjectName("label_inventory_title")
        self.frame = QtWidgets.QFrame(self.user_info1)
        self.frame.setGeometry(QtCore.QRect(180, 110, 521, 421))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(19, 19, 481, 351))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.formLayoutWidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.plainTextEdit)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(230, 380, 80, 24))
        self.pushButton.setObjectName("pushButton")
        self.user_info.addTab(self.user_info1, "")
        self.btn_logout = QtWidgets.QPushButton(self.centralwidget)
        self.btn_logout.setGeometry(QtCore.QRect(800, 10, 80, 24))
        self.btn_logout.setObjectName("btn_logout")
        self.label_login_username = QtWidgets.QLabel(self.centralwidget)
        self.label_login_username.setGeometry(QtCore.QRect(10, 10, 201, 16))
        self.label_login_username.setObjectName("label_login_username")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.user_info.setCurrentIndex(0)
        self.btn_list_show.clicked.connect(MainWindow.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_list_name_0.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Harry Patter</span></p></body></html>"))
        self.label_list_quantity_0.setText(_translate("MainWindow", "<html><head/><body><p>quntity : 25</p></body></html>"))
        self.label_list_author_0.setText(_translate("MainWindow", "<html><head/><body><p>by : Wilson miler</p></body></html>"))
        self.label_list_price_0.setText(_translate("MainWindow", "<html><head/><body><p>price : 12000 $</p></body></html>"))
        self.label_list_publisher_0.setText(_translate("MainWindow", "<html><head/><body><p>Publisher : tolo</p></body></html>"))
        self.btn_list_buy_0.setText(_translate("MainWindow", "Buy"))
        self.btn_list_search.setText(_translate("MainWindow", "Search"))
        self.checkBox_list_lp.setText(_translate("MainWindow", "lowest price"))
        self.checkBox_list_ex.setText(_translate("MainWindow", "expensive"))
        self.checkBox_list_ms.setText(_translate("MainWindow", "Most Sold"))
        self.checkBox_list_ls.setText(_translate("MainWindow", "Least Sold"))
        self.btn_list_show.setText(_translate("MainWindow", "Show"))
        self.checkBox_list_d.setText(_translate("MainWindow", "Date"))
        self.checkBox_list_q.setText(_translate("MainWindow", "quantity"))
        self.user_info.setTabText(self.user_info.indexOf(self.list), _translate("MainWindow", "Book List"))
        item = self.tableWidget_order.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_order.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget_order.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Book"))
        item = self.tableWidget_order.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "User"))
        item = self.tableWidget_order.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Publisher"))
        item = self.tableWidget_order.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date added"))
        item = self.tableWidget_order.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.tableWidget_order.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Price"))
        item = self.tableWidget_order.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Total Price"))
        __sortingEnabled = self.tableWidget_order.isSortingEnabled()
        self.tableWidget_order.setSortingEnabled(False)
        item = self.tableWidget_order.item(0, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_order.item(0, 1)
        item.setText(_translate("MainWindow", "Harry"))
        item = self.tableWidget_order.item(0, 2)
        item.setText(_translate("MainWindow", "Nrouzy"))
        item = self.tableWidget_order.item(0, 3)
        item.setText(_translate("MainWindow", "tolo"))
        item = self.tableWidget_order.item(0, 4)
        item.setText(_translate("MainWindow", "12/03/9"))
        item = self.tableWidget_order.item(0, 5)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_order.item(0, 6)
        item.setText(_translate("MainWindow", "1200"))
        item = self.tableWidget_order.item(0, 7)
        item.setText(_translate("MainWindow", "2400"))
        self.tableWidget_order.setSortingEnabled(__sortingEnabled)
        self.label_order_title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">My Orders</span></p></body></html>"))
        self.user_info.setTabText(self.user_info.indexOf(self.orders), _translate("MainWindow", "Orders"))
        self.label_inventory_title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Online Book Store Info</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.label_2.setText(_translate("MainWindow", "Last Name"))
        self.label_3.setText(_translate("MainWindow", "Phone Number"))
        self.label_4.setText(_translate("MainWindow", "Address"))
        self.lineEdit.setText(_translate("MainWindow", "noroozi"))
        self.lineEdit_5.setText(_translate("MainWindow", "mohamad"))
        self.lineEdit_4.setText(_translate("MainWindow", "09126542563"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "iran , tehran ,32"))
        self.label_5.setText(_translate("MainWindow", "Username"))
        self.lineEdit_2.setText(_translate("MainWindow", "Norouzy"))
        self.label_6.setText(_translate("MainWindow", "Password"))
        self.lineEdit_3.setText(_translate("MainWindow", "123456"))
        self.pushButton.setText(_translate("MainWindow", "Update"))
        self.user_info.setTabText(self.user_info.indexOf(self.user_info1), _translate("MainWindow", "Info"))
        self.btn_logout.setText(_translate("MainWindow", "Log out"))
        self.label_login_username.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Norouzy</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
